root: true
parserOptions:
  parser: 'babel-eslint'
  ecmaVersion: '2017'
  sourceType: 'module'
env:
  browser: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
plugins:
  - 'vue'
rules:
  space-before-function-paren:
    - 'error'
    - anonymous: 'always'
      named: 'ignore'
      asyncArrow: 'always'
  vue/component-name-in-template-casing:
    - 'error'
    - 'kebab-case'
  vue/max-attributes-per-line:
    - 'error'
    - singleline: 3
      multiline:
        max: 1
        allowFirstLine: false
  vue/singleline-html-element-content-newline:
    - 'error'
    - ignoreWhenNoAttributes: true
      ignores:
        - 'pre'
        - 'textarea'
