root: true
parser: 'babel-eslint'
env:
  browser: true
  node: true
extends: 'standard'
plugins:
  - 'html'
rules:
  space-before-function-paren:
    - 'error'
    - anonymous: 'always'
      named: 'ignore'
      asyncArrow: 'always'
