---
language: node_js
node_js:
  - 'stable'
env:
  secure: TFvEW9iHFP0GLaEJXvaOw6XcvXSskLVU+Sexko3VG4FkzaY+PAUQg2Wgt5JlBseQLaQBVC2uIbBO44XrVHW4Wqg5bInzLndTyonHUkE2ViIG06OmklaaHMrmSocTFHgnhvvV8GcLF+tVw5KXLIGyehCNJtVuHsR24ICISphe1J6nvQDtdtA9O9b52YzHy9MmVUPWPsPkXjGZ2+r67AEp8qSFp9suoHu9QmifOPLObfD2AoXx9DkWZrpsbdzOAPlJeQ9lArodHciOTanVn1exxe6YpoeqPZZ2GlP4DXH13iYIzgmZb59zuGy966QbcQ2xPcV0fEeMLAzHXmBgmrQw8xf15idtwL6z3UTNrYkRiZz4hHCdC/8NGY7ZcYkHCCCzH3yE5zCa1EQzOYRUk/d8h8DusjA0Lw2J0Tt70ooXHUlwwm9Ar/evYaNknWPS+z/gfRDz7BQZpwRcj6SoPpG6caINSd4BOEp/3pgyE4jEvJoYGQUuQQ2a83NznxrS7vhRj6TS5GqmmoR+Hy/2tpBhveMyJ1ylrmkSP9pz6W6+LuLjq1FXLC+UN9seYhkg7EgrMZJh0eWynBX9eElat6wMtOyojLx/FNJi4RqrChwrr2cmR3a5dxx4+xZFxQ3h1C1DjmYdvzTbug94AVSr+pUtsmNzv5VJsSZhfxh2azDvAOg=
cache: yarn
script:
  - yarn lint
  - yarn generate
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: source
