---
language: node_js
node_js:
  - 'lts/*'
env:
  secure: TFvEW9iHFP0GLaEJXvaOw6XcvXSskLVU+Sexko3VG4FkzaY+PAUQg2Wgt5JlBseQLaQBVC2uIbBO44XrVHW4Wqg5bInzLndTyonHUkE2ViIG06OmklaaHMrmSocTFHgnhvvV8GcLF+tVw5KXLIGyehCNJtVuHsR24ICISphe1J6nvQDtdtA9O9b52YzHy9MmVUPWPsPkXjGZ2+r67AEp8qSFp9suoHu9QmifOPLObfD2AoXx9DkWZrpsbdzOAPlJeQ9lArodHciOTanVn1exxe6YpoeqPZZ2GlP4DXH13iYIzgmZb59zuGy966QbcQ2xPcV0fEeMLAzHXmBgmrQw8xf15idtwL6z3UTNrYkRiZz4hHCdC/8NGY7ZcYkHCCCzH3yE5zCa1EQzOYRUk/d8h8DusjA0Lw2J0Tt70ooXHUlwwm9Ar/evYaNknWPS+z/gfRDz7BQZpwRcj6SoPpG6caINSd4BOEp/3pgyE4jEvJoYGQUuQQ2a83NznxrS7vhRj6TS5GqmmoR+Hy/2tpBhveMyJ1ylrmkSP9pz6W6+LuLjq1FXLC+UN9seYhkg7EgrMZJh0eWynBX9eElat6wMtOyojLx/FNJi4RqrChwrr2cmR3a5dxx4+xZFxQ3h1C1DjmYdvzTbug94AVSr+pUtsmNzv5VJsSZhfxh2azDvAOg=
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn generate
  - yarn dropcss
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: source
notifications:
  email: false
  slack:
    secure: CuL91Sv91fLh3QzQOAVp87qBqynTHbizhfWV9oxMVy5N82LuRyd5PylIbPrE5BcyWvJtmy70OauXybK9MC+e39jiq17Zq2L5eCLytWehnEYxaWmdwPwAdjC7+nGeMcpA0XRZi+chmeYPQNtKg+8/R2QKnYRpuacubRtQXc+LObppv9AYcuoRWKeA0GG89itHwzZkcOb1HiIBmpMemei2hzN/pMj9mCIGnsR1fmm45jc/XFmERiuOiJMYf5PcqJwTy9LRBq0niH+b2XRkXXrp8w4pGnMzOqprp70H9eI7sk42SIuONhQ6GTs35LQzhoSlmK7VwAbqN66o7ZWHuFwrO26gLo89JAQRAsQww7oKVBGMIwMAmQnPb/lZu0yuao3AEq0dHeeBLvT8qFgg7iKOWyshn2kh8KVgZ2tY0OYGGDJZaINpIifumiWC+2ntto/GS8J8Yay7R22PvC4WUGdc1v1wZG3sUs8fIOnlDFcGvjSj09ipiB+ZusGMD7cT8JxE1loIeUmmHCxnuCajPvKOPyX0/v4SiGYaopKJQ3j9gr71k7TPXoENbekCjYv1odakiECS2Hwb6VQ000Y7kCkN21mtQmHHXLBpj74FIpEQt2+nclwoIQqeOMJGmVTB1122H7SIXq/BBOdrhx0uWGw5mfF0FxwA4jjXTHomuIJjWXU=
